org.gradle.jvmargs=-Xmx4G
loom.platform=neoforge

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
yarn_mappings_patch_neoforge_version=1.21+build.4
neoforge_version=21.1.201
loom_version=1.11-SNAPSHOT

mod_version=1.1.0
maven_group=com.example
archives_base_name=dungeon-difficulty-addition-neoforge

dungeon_difficulty_modrinth_project=ENZmbSFZ
dungeon_difficulty_modrinth_version=XAxRmwMM
jewelry_modrinth_project=sNJAIjUm
jewelry_modrinth_version=7N47QYpl
relics_modrinth_project=BDQucwF0
relics_modrinth_version=9q085tSI
tiny_config_version=3.0.0-neoforge
accessories_version=1.1.0-beta.48+1.21.1
spell_engine_curseforge_project=807653
spell_engine_curseforge_file=8698175
